name: Build

on: [ push, pull_request ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: '16.2'
      - name: Pre-install
        run: |
          yarn
          yarn global add expo-cli
      - name: Run Checks
        run: |
          yarn lint
          yarn test
      # - name: Run Build
      #   run: |
      #     yarn web:build
      - name: Run check git
        run: |
          git diff --quiet --exit-code --cached