name: Build

on: [ push, pull_request ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: '12.x'
      - name: Pre-install
        run: |
          yarn
      - name: Run Build
        run: |
          yarn web:build
      - name: Run check git
        run: |
          git diff --quiet --exit-code --cached